%%
%% Autogenerated by Thrift Compiler (0.14.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-ifndef(_note_store_included).
-define(_note_store_included, yeah).
-include("note_store_types.hrl").

-endif.
