%%
%% Autogenerated by Thrift Compiler (0.14.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-ifndef(_types_types_included).
-define(_types_types_included, yeah).
-include("limits_types.hrl").


-define(TYPES_PRIVILEGELEVEL_NORMAL, 1).
-define(TYPES_PRIVILEGELEVEL_PREMIUM, 3).
-define(TYPES_PRIVILEGELEVEL_VIP, 5).
-define(TYPES_PRIVILEGELEVEL_MANAGER, 7).
-define(TYPES_PRIVILEGELEVEL_SUPPORT, 8).
-define(TYPES_PRIVILEGELEVEL_ADMIN, 9).

-define(TYPES_SERVICELEVEL_BASIC, 1).
-define(TYPES_SERVICELEVEL_PLUS, 2).
-define(TYPES_SERVICELEVEL_PREMIUM, 3).
-define(TYPES_SERVICELEVEL_BUSINESS, 4).

-define(TYPES_QUERYFORMAT_USER, 1).
-define(TYPES_QUERYFORMAT_SEXP, 2).

-define(TYPES_NOTESORTORDER_CREATED, 1).
-define(TYPES_NOTESORTORDER_UPDATED, 2).
-define(TYPES_NOTESORTORDER_RELEVANCE, 3).
-define(TYPES_NOTESORTORDER_UPDATE_SEQUENCE_NUMBER, 4).
-define(TYPES_NOTESORTORDER_TITLE, 5).

-define(TYPES_PREMIUMORDERSTATUS_NONE, 0).
-define(TYPES_PREMIUMORDERSTATUS_PENDING, 1).
-define(TYPES_PREMIUMORDERSTATUS_ACTIVE, 2).
-define(TYPES_PREMIUMORDERSTATUS_FAILED, 3).
-define(TYPES_PREMIUMORDERSTATUS_CANCELLATION_PENDING, 4).
-define(TYPES_PREMIUMORDERSTATUS_CANCELED, 5).

-define(TYPES_SHAREDNOTEBOOKPRIVILEGELEVEL_READ_NOTEBOOK, 0).
-define(TYPES_SHAREDNOTEBOOKPRIVILEGELEVEL_MODIFY_NOTEBOOK_PLUS_ACTIVITY, 1).
-define(TYPES_SHAREDNOTEBOOKPRIVILEGELEVEL_READ_NOTEBOOK_PLUS_ACTIVITY, 2).
-define(TYPES_SHAREDNOTEBOOKPRIVILEGELEVEL_GROUP, 3).
-define(TYPES_SHAREDNOTEBOOKPRIVILEGELEVEL_FULL_ACCESS, 4).
-define(TYPES_SHAREDNOTEBOOKPRIVILEGELEVEL_BUSINESS_FULL_ACCESS, 5).

-define(TYPES_SHAREDNOTEPRIVILEGELEVEL_READ_NOTE, 0).
-define(TYPES_SHAREDNOTEPRIVILEGELEVEL_MODIFY_NOTE, 1).
-define(TYPES_SHAREDNOTEPRIVILEGELEVEL_FULL_ACCESS, 2).

-define(TYPES_SPONSOREDGROUPROLE_GROUP_MEMBER, 1).
-define(TYPES_SPONSOREDGROUPROLE_GROUP_ADMIN, 2).
-define(TYPES_SPONSOREDGROUPROLE_GROUP_OWNER, 3).

-define(TYPES_BUSINESSUSERROLE_ADMIN, 1).
-define(TYPES_BUSINESSUSERROLE_NORMAL, 2).

-define(TYPES_BUSINESSUSERSTATUS_ACTIVE, 1).
-define(TYPES_BUSINESSUSERSTATUS_DEACTIVATED, 2).

-define(TYPES_SHAREDNOTEBOOKINSTANCERESTRICTIONS_ASSIGNED, 1).
-define(TYPES_SHAREDNOTEBOOKINSTANCERESTRICTIONS_NO_SHARED_NOTEBOOKS, 2).

-define(TYPES_REMINDEREMAILCONFIG_DO_NOT_SEND, 1).
-define(TYPES_REMINDEREMAILCONFIG_SEND_DAILY_EMAIL, 2).

-define(TYPES_BUSINESSINVITATIONSTATUS_APPROVED, 0).
-define(TYPES_BUSINESSINVITATIONSTATUS_REQUESTED, 1).
-define(TYPES_BUSINESSINVITATIONSTATUS_REDEEMED, 2).

-define(TYPES_CONTACTTYPE_EVERNOTE, 1).
-define(TYPES_CONTACTTYPE_SMS, 2).
-define(TYPES_CONTACTTYPE_FACEBOOK, 3).
-define(TYPES_CONTACTTYPE_EMAIL, 4).
-define(TYPES_CONTACTTYPE_TWITTER, 5).
-define(TYPES_CONTACTTYPE_LINKEDIN, 6).

-define(TYPES_ENTITYTYPE_NOTE, 1).
-define(TYPES_ENTITYTYPE_NOTEBOOK, 2).
-define(TYPES_ENTITYTYPE_WORKSPACE, 3).

-define(TYPES_RECIPIENTSTATUS_NOT_IN_MY_LIST, 1).
-define(TYPES_RECIPIENTSTATUS_IN_MY_LIST, 2).
-define(TYPES_RECIPIENTSTATUS_IN_MY_LIST_AND_DEFAULT_NOTEBOOK, 3).

-define(TYPES_CANMOVETOCONTAINERSTATUS_CAN_BE_MOVED, 1).
-define(TYPES_CANMOVETOCONTAINERSTATUS_INSUFFICIENT_ENTITY_PRIVILEGE, 2).
-define(TYPES_CANMOVETOCONTAINERSTATUS_INSUFFICIENT_CONTAINER_PRIVILEGE, 3).

-define(TYPES_RELATEDCONTENTTYPE_NEWS_ARTICLE, 1).
-define(TYPES_RELATEDCONTENTTYPE_PROFILE_PERSON, 2).
-define(TYPES_RELATEDCONTENTTYPE_PROFILE_ORGANIZATION, 3).
-define(TYPES_RELATEDCONTENTTYPE_REFERENCE_MATERIAL, 4).

-define(TYPES_RELATEDCONTENTACCESS_NOT_ACCESSIBLE, 0).
-define(TYPES_RELATEDCONTENTACCESS_DIRECT_LINK_ACCESS_OK, 1).
-define(TYPES_RELATEDCONTENTACCESS_DIRECT_LINK_LOGIN_REQUIRED, 2).
-define(TYPES_RELATEDCONTENTACCESS_DIRECT_LINK_EMBEDDED_VIEW, 3).

-define(TYPES_USERIDENTITYTYPE_EVERNOTE_USERID, 1).
-define(TYPES_USERIDENTITYTYPE_EMAIL, 2).
-define(TYPES_USERIDENTITYTYPE_IDENTITYID, 3).

%% struct 'Data'

-record('Data', {'bodyHash' :: string() | binary() | 'undefined',
                 'size' :: integer() | 'undefined',
                 'body' :: string() | binary() | 'undefined'}).
-type 'Data'() :: #'Data'{}.

%% struct 'UserAttributes'

-record('UserAttributes', {'defaultLocationName' :: string() | binary() | 'undefined',
                           'defaultLatitude' :: float() | 'undefined',
                           'defaultLongitude' :: float() | 'undefined',
                           'preactivation' :: boolean() | 'undefined',
                           'viewedPromotions' :: list() | 'undefined',
                           'incomingEmailAddress' :: string() | binary() | 'undefined',
                           'recentMailedAddresses' :: list() | 'undefined',
                           'comments' :: string() | binary() | 'undefined',
                           'dateAgreedToTermsOfService' :: integer() | 'undefined',
                           'maxReferrals' :: integer() | 'undefined',
                           'referralCount' :: integer() | 'undefined',
                           'refererCode' :: string() | binary() | 'undefined',
                           'sentEmailDate' :: integer() | 'undefined',
                           'sentEmailCount' :: integer() | 'undefined',
                           'dailyEmailLimit' :: integer() | 'undefined',
                           'emailOptOutDate' :: integer() | 'undefined',
                           'partnerEmailOptInDate' :: integer() | 'undefined',
                           'preferredLanguage' :: string() | binary() | 'undefined',
                           'preferredCountry' :: string() | binary() | 'undefined',
                           'clipFullPage' :: boolean() | 'undefined',
                           'twitterUserName' :: string() | binary() | 'undefined',
                           'twitterId' :: string() | binary() | 'undefined',
                           'groupName' :: string() | binary() | 'undefined',
                           'recognitionLanguage' :: string() | binary() | 'undefined',
                           'referralProof' :: string() | binary() | 'undefined',
                           'educationalDiscount' :: boolean() | 'undefined',
                           'businessAddress' :: string() | binary() | 'undefined',
                           'hideSponsorBilling' :: boolean() | 'undefined',
                           'useEmailAutoFiling' :: boolean() | 'undefined',
                           'reminderEmailConfig' :: integer() | 'undefined',
                           'emailAddressLastConfirmed' :: integer() | 'undefined',
                           'passwordUpdated' :: integer() | 'undefined',
                           'salesforcePushEnabled' :: boolean() | 'undefined',
                           'shouldLogClientEvent' :: boolean() | 'undefined',
                           'optOutMachineLearning' :: boolean() | 'undefined'}).
-type 'UserAttributes'() :: #'UserAttributes'{}.

%% struct 'BusinessUserAttributes'

-record('BusinessUserAttributes', {'title' :: string() | binary() | 'undefined',
                                   'location' :: string() | binary() | 'undefined',
                                   'department' :: string() | binary() | 'undefined',
                                   'mobilePhone' :: string() | binary() | 'undefined',
                                   'linkedInProfileUrl' :: string() | binary() | 'undefined',
                                   'workPhone' :: string() | binary() | 'undefined',
                                   'companyStartDate' :: integer() | 'undefined'}).
-type 'BusinessUserAttributes'() :: #'BusinessUserAttributes'{}.

%% struct 'Accounting'

-record('Accounting', {'uploadLimitEnd' :: integer() | 'undefined',
                       'uploadLimitNextMonth' :: integer() | 'undefined',
                       'premiumServiceStatus' :: integer() | 'undefined',
                       'premiumOrderNumber' :: string() | binary() | 'undefined',
                       'premiumCommerceService' :: string() | binary() | 'undefined',
                       'premiumServiceStart' :: integer() | 'undefined',
                       'premiumServiceSKU' :: string() | binary() | 'undefined',
                       'lastSuccessfulCharge' :: integer() | 'undefined',
                       'lastFailedCharge' :: integer() | 'undefined',
                       'lastFailedChargeReason' :: string() | binary() | 'undefined',
                       'nextPaymentDue' :: integer() | 'undefined',
                       'premiumLockUntil' :: integer() | 'undefined',
                       'updated' :: integer() | 'undefined',
                       'premiumSubscriptionNumber' :: string() | binary() | 'undefined',
                       'lastRequestedCharge' :: integer() | 'undefined',
                       'currency' :: string() | binary() | 'undefined',
                       'unitPrice' :: integer() | 'undefined',
                       'businessId' :: integer() | 'undefined',
                       'businessName' :: string() | binary() | 'undefined',
                       'businessRole' :: integer() | 'undefined',
                       'unitDiscount' :: integer() | 'undefined',
                       'nextChargeDate' :: integer() | 'undefined',
                       'availablePoints' :: integer() | 'undefined'}).
-type 'Accounting'() :: #'Accounting'{}.

%% struct 'BusinessUserInfo'

-record('BusinessUserInfo', {'businessId' :: integer() | 'undefined',
                             'businessName' :: string() | binary() | 'undefined',
                             'role' :: integer() | 'undefined',
                             'email' :: string() | binary() | 'undefined',
                             'updated' :: integer() | 'undefined'}).
-type 'BusinessUserInfo'() :: #'BusinessUserInfo'{}.

%% struct 'AccountLimits'

-record('AccountLimits', {'userMailLimitDaily' :: integer() | 'undefined',
                          'noteSizeMax' :: integer() | 'undefined',
                          'resourceSizeMax' :: integer() | 'undefined',
                          'userLinkedNotebookMax' :: integer() | 'undefined',
                          'uploadLimit' :: integer() | 'undefined',
                          'userNoteCountMax' :: integer() | 'undefined',
                          'userNotebookCountMax' :: integer() | 'undefined',
                          'userTagCountMax' :: integer() | 'undefined',
                          'noteTagCountMax' :: integer() | 'undefined',
                          'userSavedSearchesMax' :: integer() | 'undefined',
                          'noteResourceCountMax' :: integer() | 'undefined'}).
-type 'AccountLimits'() :: #'AccountLimits'{}.

%% struct 'User'

-record('User', {'id' :: integer() | 'undefined',
                 'username' :: string() | binary() | 'undefined',
                 'email' :: string() | binary() | 'undefined',
                 'name' :: string() | binary() | 'undefined',
                 'timezone' :: string() | binary() | 'undefined',
                 'privilege' :: integer() | 'undefined',
                 'serviceLevel' :: integer() | 'undefined',
                 'created' :: integer() | 'undefined',
                 'updated' :: integer() | 'undefined',
                 'deleted' :: integer() | 'undefined',
                 'active' :: boolean() | 'undefined',
                 'shardId' :: string() | binary() | 'undefined',
                 'attributes' :: 'UserAttributes'() | 'undefined',
                 'accounting' :: 'Accounting'() | 'undefined',
                 'businessUserInfo' :: 'BusinessUserInfo'() | 'undefined',
                 'photoUrl' :: string() | binary() | 'undefined',
                 'photoLastUpdated' :: integer() | 'undefined',
                 'accountLimits' :: 'AccountLimits'() | 'undefined'}).
-type 'User'() :: #'User'{}.

%% struct 'Contact'

-record('Contact', {'name' :: string() | binary() | 'undefined',
                    'id' :: string() | binary() | 'undefined',
                    'type' :: integer() | 'undefined',
                    'photoUrl' :: string() | binary() | 'undefined',
                    'photoLastUpdated' :: integer() | 'undefined',
                    'messagingPermit' :: string() | binary() | 'undefined',
                    'messagingPermitExpires' :: integer() | 'undefined'}).
-type 'Contact'() :: #'Contact'{}.

%% struct 'Identity'

-record('Identity', {'id' :: integer(),
                     'contact' :: 'Contact'() | 'undefined',
                     'userId' :: integer() | 'undefined',
                     'deactivated' :: boolean() | 'undefined',
                     'sameBusiness' :: boolean() | 'undefined',
                     'blocked' :: boolean() | 'undefined',
                     'userConnected' :: boolean() | 'undefined',
                     'eventId' :: integer() | 'undefined'}).
-type 'Identity'() :: #'Identity'{}.

%% struct 'Tag'

-record('Tag', {'guid' :: string() | binary() | 'undefined',
                'name' :: string() | binary() | 'undefined',
                'parentGuid' :: string() | binary() | 'undefined',
                'updateSequenceNum' :: integer() | 'undefined'}).
-type 'Tag'() :: #'Tag'{}.

%% struct 'LazyMap'

-record('LazyMap', {'keysOnly' :: sets:set() | 'undefined',
                    'fullMap' :: dict:dict() | 'undefined'}).
-type 'LazyMap'() :: #'LazyMap'{}.

%% struct 'ResourceAttributes'

-record('ResourceAttributes', {'sourceURL' :: string() | binary() | 'undefined',
                               'timestamp' :: integer() | 'undefined',
                               'latitude' :: float() | 'undefined',
                               'longitude' :: float() | 'undefined',
                               'altitude' :: float() | 'undefined',
                               'cameraMake' :: string() | binary() | 'undefined',
                               'cameraModel' :: string() | binary() | 'undefined',
                               'clientWillIndex' :: boolean() | 'undefined',
                               'recoType' :: string() | binary() | 'undefined',
                               'fileName' :: string() | binary() | 'undefined',
                               'attachment' :: boolean() | 'undefined',
                               'applicationData' :: 'LazyMap'() | 'undefined'}).
-type 'ResourceAttributes'() :: #'ResourceAttributes'{}.

%% struct 'Resource'

-record('Resource', {'guid' :: string() | binary() | 'undefined',
                     'noteGuid' :: string() | binary() | 'undefined',
                     'data' :: 'Data'() | 'undefined',
                     'mime' :: string() | binary() | 'undefined',
                     'width' :: integer() | 'undefined',
                     'height' :: integer() | 'undefined',
                     'duration' :: integer() | 'undefined',
                     'active' :: boolean() | 'undefined',
                     'recognition' :: 'Data'() | 'undefined',
                     'attributes' :: 'ResourceAttributes'() | 'undefined',
                     'updateSequenceNum' :: integer() | 'undefined',
                     'alternateData' :: 'Data'() | 'undefined'}).
-type 'Resource'() :: #'Resource'{}.

%% struct 'NoteAttributes'

-record('NoteAttributes', {'subjectDate' :: integer() | 'undefined',
                           'latitude' :: float() | 'undefined',
                           'longitude' :: float() | 'undefined',
                           'altitude' :: float() | 'undefined',
                           'author' :: string() | binary() | 'undefined',
                           'source' :: string() | binary() | 'undefined',
                           'sourceURL' :: string() | binary() | 'undefined',
                           'sourceApplication' :: string() | binary() | 'undefined',
                           'shareDate' :: integer() | 'undefined',
                           'reminderOrder' :: integer() | 'undefined',
                           'reminderDoneTime' :: integer() | 'undefined',
                           'reminderTime' :: integer() | 'undefined',
                           'placeName' :: string() | binary() | 'undefined',
                           'contentClass' :: string() | binary() | 'undefined',
                           'applicationData' :: 'LazyMap'() | 'undefined',
                           'lastEditedBy' :: string() | binary() | 'undefined',
                           'classifications' :: dict:dict() | 'undefined',
                           'creatorId' :: integer() | 'undefined',
                           'lastEditorId' :: integer() | 'undefined',
                           'sharedWithBusiness' :: boolean() | 'undefined',
                           'conflictSourceNoteGuid' :: string() | binary() | 'undefined',
                           'noteTitleQuality' :: integer() | 'undefined'}).
-type 'NoteAttributes'() :: #'NoteAttributes'{}.

%% struct 'SharedNote'

-record('SharedNote', {'sharerUserID' :: integer() | 'undefined',
                       'recipientIdentity' :: 'Identity'() | 'undefined',
                       'privilege' :: integer() | 'undefined',
                       'serviceCreated' :: integer() | 'undefined',
                       'serviceUpdated' :: integer() | 'undefined',
                       'serviceAssigned' :: integer() | 'undefined'}).
-type 'SharedNote'() :: #'SharedNote'{}.

%% struct 'NoteRestrictions'

-record('NoteRestrictions', {'noUpdateTitle' :: boolean() | 'undefined',
                             'noUpdateContent' :: boolean() | 'undefined',
                             'noEmail' :: boolean() | 'undefined',
                             'noShare' :: boolean() | 'undefined',
                             'noSharePublicly' :: boolean() | 'undefined'}).
-type 'NoteRestrictions'() :: #'NoteRestrictions'{}.

%% struct 'NoteLimits'

-record('NoteLimits', {'noteResourceCountMax' :: integer() | 'undefined',
                       'uploadLimit' :: integer() | 'undefined',
                       'resourceSizeMax' :: integer() | 'undefined',
                       'noteSizeMax' :: integer() | 'undefined',
                       'uploaded' :: integer() | 'undefined'}).
-type 'NoteLimits'() :: #'NoteLimits'{}.

%% struct 'Note'

-record('Note', {'guid' :: string() | binary() | 'undefined',
                 'title' :: string() | binary() | 'undefined',
                 'content' :: string() | binary() | 'undefined',
                 'contentHash' :: string() | binary() | 'undefined',
                 'contentLength' :: integer() | 'undefined',
                 'created' :: integer() | 'undefined',
                 'updated' :: integer() | 'undefined',
                 'deleted' :: integer() | 'undefined',
                 'active' :: boolean() | 'undefined',
                 'updateSequenceNum' :: integer() | 'undefined',
                 'notebookGuid' :: string() | binary() | 'undefined',
                 'tagGuids' :: list() | 'undefined',
                 'resources' :: list() | 'undefined',
                 'attributes' :: 'NoteAttributes'() | 'undefined',
                 'tagNames' :: list() | 'undefined',
                 'sharedNotes' :: list() | 'undefined',
                 'restrictions' :: 'NoteRestrictions'() | 'undefined',
                 'limits' :: 'NoteLimits'() | 'undefined'}).
-type 'Note'() :: #'Note'{}.

%% struct 'Publishing'

-record('Publishing', {'uri' :: string() | binary() | 'undefined',
                       'order' :: integer() | 'undefined',
                       'ascending' :: boolean() | 'undefined',
                       'publicDescription' :: string() | binary() | 'undefined'}).
-type 'Publishing'() :: #'Publishing'{}.

%% struct 'BusinessNotebook'

-record('BusinessNotebook', {'notebookDescription' :: string() | binary() | 'undefined',
                             'privilege' :: integer() | 'undefined',
                             'recommended' :: boolean() | 'undefined'}).
-type 'BusinessNotebook'() :: #'BusinessNotebook'{}.

%% struct 'SavedSearchScope'

-record('SavedSearchScope', {'includeAccount' :: boolean() | 'undefined',
                             'includePersonalLinkedNotebooks' :: boolean() | 'undefined',
                             'includeBusinessLinkedNotebooks' :: boolean() | 'undefined'}).
-type 'SavedSearchScope'() :: #'SavedSearchScope'{}.

%% struct 'SavedSearch'

-record('SavedSearch', {'guid' :: string() | binary() | 'undefined',
                        'name' :: string() | binary() | 'undefined',
                        'query' :: string() | binary() | 'undefined',
                        'format' :: integer() | 'undefined',
                        'updateSequenceNum' :: integer() | 'undefined',
                        'scope' :: 'SavedSearchScope'() | 'undefined'}).
-type 'SavedSearch'() :: #'SavedSearch'{}.

%% struct 'SharedNotebookRecipientSettings'

-record('SharedNotebookRecipientSettings', {'reminderNotifyEmail' :: boolean() | 'undefined',
                                            'reminderNotifyInApp' :: boolean() | 'undefined'}).
-type 'SharedNotebookRecipientSettings'() :: #'SharedNotebookRecipientSettings'{}.

%% struct 'NotebookRecipientSettings'

-record('NotebookRecipientSettings', {'reminderNotifyEmail' :: boolean() | 'undefined',
                                      'reminderNotifyInApp' :: boolean() | 'undefined',
                                      'inMyList' :: boolean() | 'undefined',
                                      'stack' :: string() | binary() | 'undefined',
                                      'recipientStatus' :: integer() | 'undefined'}).
-type 'NotebookRecipientSettings'() :: #'NotebookRecipientSettings'{}.

%% struct 'SharedNotebook'

-record('SharedNotebook', {'id' :: integer() | 'undefined',
                           'userId' :: integer() | 'undefined',
                           'notebookGuid' :: string() | binary() | 'undefined',
                           'email' :: string() | binary() | 'undefined',
                           'recipientIdentityId' :: integer() | 'undefined',
                           'notebookModifiable' :: boolean() | 'undefined',
                           'serviceCreated' :: integer() | 'undefined',
                           'serviceUpdated' :: integer() | 'undefined',
                           'globalId' :: string() | binary() | 'undefined',
                           'username' :: string() | binary() | 'undefined',
                           'privilege' :: integer() | 'undefined',
                           'recipientSettings' :: 'SharedNotebookRecipientSettings'() | 'undefined',
                           'sharerUserId' :: integer() | 'undefined',
                           'recipientUsername' :: string() | binary() | 'undefined',
                           'recipientUserId' :: integer() | 'undefined',
                           'serviceAssigned' :: integer() | 'undefined'}).
-type 'SharedNotebook'() :: #'SharedNotebook'{}.

%% struct 'CanMoveToContainerRestrictions'

-record('CanMoveToContainerRestrictions', {'canMoveToContainer' :: integer() | 'undefined'}).
-type 'CanMoveToContainerRestrictions'() :: #'CanMoveToContainerRestrictions'{}.

%% struct 'NotebookRestrictions'

-record('NotebookRestrictions', {'noReadNotes' :: boolean() | 'undefined',
                                 'noCreateNotes' :: boolean() | 'undefined',
                                 'noUpdateNotes' :: boolean() | 'undefined',
                                 'noExpungeNotes' :: boolean() | 'undefined',
                                 'noShareNotes' :: boolean() | 'undefined',
                                 'noEmailNotes' :: boolean() | 'undefined',
                                 'noSendMessageToRecipients' :: boolean() | 'undefined',
                                 'noUpdateNotebook' :: boolean() | 'undefined',
                                 'noExpungeNotebook' :: boolean() | 'undefined',
                                 'noSetDefaultNotebook' :: boolean() | 'undefined',
                                 'noSetNotebookStack' :: boolean() | 'undefined',
                                 'noPublishToPublic' :: boolean() | 'undefined',
                                 'noPublishToBusinessLibrary' :: boolean() | 'undefined',
                                 'noCreateTags' :: boolean() | 'undefined',
                                 'noUpdateTags' :: boolean() | 'undefined',
                                 'noExpungeTags' :: boolean() | 'undefined',
                                 'noSetParentTag' :: boolean() | 'undefined',
                                 'noCreateSharedNotebooks' :: boolean() | 'undefined',
                                 'updateWhichSharedNotebookRestrictions' :: integer() | 'undefined',
                                 'expungeWhichSharedNotebookRestrictions' :: integer() | 'undefined',
                                 'noShareNotesWithBusiness' :: boolean() | 'undefined',
                                 'noRenameNotebook' :: boolean() | 'undefined',
                                 'noSetInMyList' :: boolean() | 'undefined',
                                 'noChangeContact' :: boolean() | 'undefined',
                                 'canMoveToContainerRestrictions' :: 'CanMoveToContainerRestrictions'() | 'undefined',
                                 'noSetReminderNotifyEmail' :: boolean() | 'undefined',
                                 'noSetReminderNotifyInApp' :: boolean() | 'undefined',
                                 'noSetRecipientSettingsStack' :: boolean() | 'undefined',
                                 'noCanMoveNote' :: boolean() | 'undefined'}).
-type 'NotebookRestrictions'() :: #'NotebookRestrictions'{}.

%% struct 'Notebook'

-record('Notebook', {'guid' :: string() | binary() | 'undefined',
                     'name' :: string() | binary() | 'undefined',
                     'updateSequenceNum' :: integer() | 'undefined',
                     'defaultNotebook' :: boolean() | 'undefined',
                     'serviceCreated' :: integer() | 'undefined',
                     'serviceUpdated' :: integer() | 'undefined',
                     'publishing' :: 'Publishing'() | 'undefined',
                     'published' :: boolean() | 'undefined',
                     'stack' :: string() | binary() | 'undefined',
                     'sharedNotebookIds' :: list() | 'undefined',
                     'sharedNotebooks' :: list() | 'undefined',
                     'businessNotebook' :: 'BusinessNotebook'() | 'undefined',
                     'contact' :: 'User'() | 'undefined',
                     'restrictions' :: 'NotebookRestrictions'() | 'undefined',
                     'recipientSettings' :: 'NotebookRecipientSettings'() | 'undefined'}).
-type 'Notebook'() :: #'Notebook'{}.

%% struct 'LinkedNotebook'

-record('LinkedNotebook', {'shareName' :: string() | binary() | 'undefined',
                           'username' :: string() | binary() | 'undefined',
                           'shardId' :: string() | binary() | 'undefined',
                           'sharedNotebookGlobalId' :: string() | binary() | 'undefined',
                           'uri' :: string() | binary() | 'undefined',
                           'guid' :: string() | binary() | 'undefined',
                           'updateSequenceNum' :: integer() | 'undefined',
                           'noteStoreUrl' :: string() | binary() | 'undefined',
                           'webApiUrlPrefix' :: string() | binary() | 'undefined',
                           'stack' :: string() | binary() | 'undefined',
                           'businessId' :: integer() | 'undefined'}).
-type 'LinkedNotebook'() :: #'LinkedNotebook'{}.

%% struct 'NotebookDescriptor'

-record('NotebookDescriptor', {'guid' :: string() | binary() | 'undefined',
                               'notebookDisplayName' :: string() | binary() | 'undefined',
                               'contactName' :: string() | binary() | 'undefined',
                               'hasSharedNotebook' :: boolean() | 'undefined',
                               'joinedUserCount' :: integer() | 'undefined'}).
-type 'NotebookDescriptor'() :: #'NotebookDescriptor'{}.

%% struct 'UserProfile'

-record('UserProfile', {'id' :: integer() | 'undefined',
                        'name' :: string() | binary() | 'undefined',
                        'email' :: string() | binary() | 'undefined',
                        'username' :: string() | binary() | 'undefined',
                        'attributes' :: 'BusinessUserAttributes'() | 'undefined',
                        'joined' :: integer() | 'undefined',
                        'photoLastUpdated' :: integer() | 'undefined',
                        'photoUrl' :: string() | binary() | 'undefined',
                        'role' :: integer() | 'undefined',
                        'status' :: integer() | 'undefined'}).
-type 'UserProfile'() :: #'UserProfile'{}.

%% struct 'RelatedContentImage'

-record('RelatedContentImage', {'url' :: string() | binary() | 'undefined',
                                'width' :: integer() | 'undefined',
                                'height' :: integer() | 'undefined',
                                'pixelRatio' :: float() | 'undefined',
                                'fileSize' :: integer() | 'undefined'}).
-type 'RelatedContentImage'() :: #'RelatedContentImage'{}.

%% struct 'RelatedContent'

-record('RelatedContent', {'contentId' :: string() | binary() | 'undefined',
                           'title' :: string() | binary() | 'undefined',
                           'url' :: string() | binary() | 'undefined',
                           'sourceId' :: string() | binary() | 'undefined',
                           'sourceUrl' :: string() | binary() | 'undefined',
                           'sourceFaviconUrl' :: string() | binary() | 'undefined',
                           'sourceName' :: string() | binary() | 'undefined',
                           'date' :: integer() | 'undefined',
                           'teaser' :: string() | binary() | 'undefined',
                           'thumbnails' :: list() | 'undefined',
                           'contentType' :: integer() | 'undefined',
                           'accessType' :: integer() | 'undefined',
                           'visibleUrl' :: string() | binary() | 'undefined',
                           'clipUrl' :: string() | binary() | 'undefined',
                           'contact' :: 'Contact'() | 'undefined',
                           'authors' :: list() | 'undefined'}).
-type 'RelatedContent'() :: #'RelatedContent'{}.

%% struct 'BusinessInvitation'

-record('BusinessInvitation', {'businessId' :: integer() | 'undefined',
                               'email' :: string() | binary() | 'undefined',
                               'role' :: integer() | 'undefined',
                               'status' :: integer() | 'undefined',
                               'requesterId' :: integer() | 'undefined',
                               'fromWorkChat' :: boolean() | 'undefined',
                               'created' :: integer() | 'undefined',
                               'mostRecentReminder' :: integer() | 'undefined'}).
-type 'BusinessInvitation'() :: #'BusinessInvitation'{}.

%% struct 'UserIdentity'

-record('UserIdentity', {'type' :: integer() | 'undefined',
                         'stringIdentifier' :: string() | binary() | 'undefined',
                         'longIdentifier' :: integer() | 'undefined'}).
-type 'UserIdentity'() :: #'UserIdentity'{}.

-endif.
