%%
%% Autogenerated by Thrift Compiler (0.14.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(note_store_types).

-include("note_store_types.hrl").

-export([struct_info/1, struct_info_ext/1, enum_info/1, enum_names/0, struct_names/0, exception_names/0]).

struct_info('SyncState') ->
  {struct, [{1, i64},
          {2, i64},
          {3, i32},
          {4, i64},
          {5, i64},
          {6, i64}]}
;

struct_info('SyncChunk') ->
  {struct, [{1, i64},
          {2, i32},
          {3, i32},
          {4, {list, {struct, {'types_types', 'Note'}}}},
          {5, {list, {struct, {'types_types', 'Notebook'}}}},
          {6, {list, {struct, {'types_types', 'Tag'}}}},
          {7, {list, {struct, {'types_types', 'SavedSearch'}}}},
          {8, {list, {struct, {'types_types', 'Resource'}}}},
          {9, {list, string}},
          {10, {list, string}},
          {11, {list, string}},
          {12, {list, string}},
          {13, {list, {struct, {'types_types', 'LinkedNotebook'}}}},
          {14, {list, string}}]}
;

struct_info('SyncChunkFilter') ->
  {struct, [{1, bool},
          {2, bool},
          {3, bool},
          {4, bool},
          {5, bool},
          {6, bool},
          {7, bool},
          {8, bool},
          {9, bool},
          {10, bool},
          {12, bool},
          {13, bool},
          {17, bool},
          {16, bool},
          {11, string},
          {15, {set, string}}]}
;

struct_info('NoteFilter') ->
  {struct, [{1, i32},
          {2, bool},
          {3, string},
          {4, string},
          {5, {list, string}},
          {6, string},
          {7, bool},
          {8, string},
          {9, bool},
          {15, bool},
          {10, string},
          {11, string},
          {12, string}]}
;

struct_info('NoteList') ->
  {struct, [{1, i32},
          {2, i32},
          {3, {list, {struct, {'types_types', 'Note'}}}},
          {4, {list, string}},
          {5, {list, string}},
          {6, i32},
          {7, string},
          {8, string}]}
;

struct_info('NoteMetadata') ->
  {struct, [{1, string},
          {2, string},
          {5, i32},
          {6, i64},
          {7, i64},
          {8, i64},
          {10, i32},
          {11, string},
          {12, {list, string}},
          {14, {struct, {'types_types', 'NoteAttributes'}}},
          {20, string},
          {21, i32}]}
;

struct_info('NotesMetadataList') ->
  {struct, [{1, i32},
          {2, i32},
          {3, {list, {struct, {'note_store_types', 'NoteMetadata'}}}},
          {4, {list, string}},
          {5, {list, string}},
          {6, i32},
          {7, string},
          {9, string}]}
;

struct_info('NotesMetadataResultSpec') ->
  {struct, [{2, bool},
          {5, bool},
          {6, bool},
          {7, bool},
          {8, bool},
          {10, bool},
          {11, bool},
          {12, bool},
          {14, bool},
          {20, bool},
          {21, bool}]}
;

struct_info('NoteCollectionCounts') ->
  {struct, [{1, {map, string, i32}},
          {2, {map, string, i32}},
          {3, i32}]}
;

struct_info('NoteResultSpec') ->
  {struct, [{1, bool},
          {2, bool},
          {3, bool},
          {4, bool},
          {5, bool},
          {6, bool},
          {7, bool},
          {8, bool}]}
;

struct_info('NoteEmailParameters') ->
  {struct, [{1, string},
          {2, {struct, {'types_types', 'Note'}}},
          {3, {list, string}},
          {4, {list, string}},
          {5, string},
          {6, string}]}
;

struct_info('NoteVersionId') ->
  {struct, [{1, i32},
          {2, i64},
          {3, i64},
          {4, string},
          {5, i32}]}
;

struct_info('RelatedQuery') ->
  {struct, [{1, string},
          {2, string},
          {3, {struct, {'note_store_types', 'NoteFilter'}}},
          {4, string},
          {5, string},
          {6, string}]}
;

struct_info('RelatedResult') ->
  {struct, [{1, {list, {struct, {'types_types', 'Note'}}}},
          {2, {list, {struct, {'types_types', 'Notebook'}}}},
          {3, {list, {struct, {'types_types', 'Tag'}}}},
          {4, {list, {struct, {'types_types', 'NotebookDescriptor'}}}},
          {5, string},
          {6, {list, {struct, {'types_types', 'UserProfile'}}}},
          {7, {list, {struct, {'types_types', 'RelatedContent'}}}},
          {8, string},
          {9, i32}]}
;

struct_info('RelatedResultSpec') ->
  {struct, [{1, i32},
          {2, i32},
          {3, i32},
          {4, bool},
          {5, bool},
          {6, bool},
          {7, i32},
          {8, i32},
          {9, {set, i32}}]}
;

struct_info('UpdateNoteIfUsnMatchesResult') ->
  {struct, [{1, {struct, {'types_types', 'Note'}}},
          {2, bool}]}
;

struct_info('ShareRelationshipRestrictions') ->
  {struct, [{1, bool},
          {2, bool},
          {3, bool},
          {4, bool}]}
;

struct_info('InvitationShareRelationship') ->
  {struct, [{1, string},
          {2, {struct, {'types_types', 'UserIdentity'}}},
          {3, i32},
          {5, i32}]}
;

struct_info('MemberShareRelationship') ->
  {struct, [{1, string},
          {2, i32},
          {3, i32},
          {4, i32},
          {5, {struct, {'note_store_types', 'ShareRelationshipRestrictions'}}},
          {6, i32}]}
;

struct_info('ShareRelationships') ->
  {struct, [{1, {list, {struct, {'note_store_types', 'InvitationShareRelationship'}}}},
          {2, {list, {struct, {'note_store_types', 'MemberShareRelationship'}}}},
          {3, {struct, {'note_store_types', 'ShareRelationshipRestrictions'}}}]}
;

struct_info('ManageNotebookSharesParameters') ->
  {struct, [{1, string},
          {2, string},
          {3, {list, {struct, {'note_store_types', 'MemberShareRelationship'}}}},
          {4, {list, {struct, {'note_store_types', 'InvitationShareRelationship'}}}},
          {5, {list, {struct, {'types_types', 'UserIdentity'}}}}]}
;

struct_info('ManageNotebookSharesError') ->
  {struct, [{1, {struct, {'types_types', 'UserIdentity'}}},
          {2, {struct, {'errors_types', 'EDAMUserException'}}},
          {3, {struct, {'errors_types', 'EDAMNotFoundException'}}}]}
;

struct_info('ManageNotebookSharesResult') ->
  {struct, [{1, {list, {struct, {'note_store_types', 'ManageNotebookSharesError'}}}}]}
;

struct_info('SharedNoteTemplate') ->
  {struct, [{1, string},
          {4, i64},
          {2, {list, {struct, {'types_types', 'Contact'}}}},
          {3, i32}]}
;

struct_info('NotebookShareTemplate') ->
  {struct, [{1, string},
          {4, i64},
          {2, {list, {struct, {'types_types', 'Contact'}}}},
          {3, i32}]}
;

struct_info('CreateOrUpdateNotebookSharesResult') ->
  {struct, [{1, i32},
          {2, {list, {struct, {'types_types', 'SharedNotebook'}}}}]}
;

struct_info('NoteShareRelationshipRestrictions') ->
  {struct, [{1, bool},
          {2, bool},
          {3, bool}]}
;

struct_info('NoteMemberShareRelationship') ->
  {struct, [{1, string},
          {2, i32},
          {3, i32},
          {4, {struct, {'note_store_types', 'NoteShareRelationshipRestrictions'}}},
          {5, i32}]}
;

struct_info('NoteInvitationShareRelationship') ->
  {struct, [{1, string},
          {2, i64},
          {3, i32},
          {5, i32}]}
;

struct_info('NoteShareRelationships') ->
  {struct, [{1, {list, {struct, {'note_store_types', 'NoteInvitationShareRelationship'}}}},
          {2, {list, {struct, {'note_store_types', 'NoteMemberShareRelationship'}}}},
          {3, {struct, {'note_store_types', 'NoteShareRelationshipRestrictions'}}}]}
;

struct_info('ManageNoteSharesParameters') ->
  {struct, [{1, string},
          {2, {list, {struct, {'note_store_types', 'NoteMemberShareRelationship'}}}},
          {3, {list, {struct, {'note_store_types', 'NoteInvitationShareRelationship'}}}},
          {4, {list, i32}},
          {5, {list, i64}}]}
;

struct_info('ManageNoteSharesError') ->
  {struct, [{1, i64},
          {2, i32},
          {3, {struct, {'errors_types', 'EDAMUserException'}}},
          {4, {struct, {'errors_types', 'EDAMNotFoundException'}}}]}
;

struct_info('ManageNoteSharesResult') ->
  {struct, [{1, {list, {struct, {'note_store_types', 'ManageNoteSharesError'}}}}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('SyncState') ->
  {struct, [{1, required, i64, 'currentTime', undefined},
          {2, required, i64, 'fullSyncBefore', undefined},
          {3, required, i32, 'updateCount', undefined},
          {4, optional, i64, 'uploaded', undefined},
          {5, optional, i64, 'userLastUpdated', undefined},
          {6, optional, i64, 'userMaxMessageEventId', undefined}]}
;

struct_info_ext('SyncChunk') ->
  {struct, [{1, required, i64, 'currentTime', undefined},
          {2, optional, i32, 'chunkHighUSN', undefined},
          {3, required, i32, 'updateCount', undefined},
          {4, optional, {list, {struct, {'types_types', 'Note'}}}, 'notes', []},
          {5, optional, {list, {struct, {'types_types', 'Notebook'}}}, 'notebooks', []},
          {6, optional, {list, {struct, {'types_types', 'Tag'}}}, 'tags', []},
          {7, optional, {list, {struct, {'types_types', 'SavedSearch'}}}, 'searches', []},
          {8, optional, {list, {struct, {'types_types', 'Resource'}}}, 'resources', []},
          {9, optional, {list, string}, 'expungedNotes', []},
          {10, optional, {list, string}, 'expungedNotebooks', []},
          {11, optional, {list, string}, 'expungedTags', []},
          {12, optional, {list, string}, 'expungedSearches', []},
          {13, optional, {list, {struct, {'types_types', 'LinkedNotebook'}}}, 'linkedNotebooks', []},
          {14, optional, {list, string}, 'expungedLinkedNotebooks', []}]}
;

struct_info_ext('SyncChunkFilter') ->
  {struct, [{1, optional, bool, 'includeNotes', undefined},
          {2, optional, bool, 'includeNoteResources', undefined},
          {3, optional, bool, 'includeNoteAttributes', undefined},
          {4, optional, bool, 'includeNotebooks', undefined},
          {5, optional, bool, 'includeTags', undefined},
          {6, optional, bool, 'includeSearches', undefined},
          {7, optional, bool, 'includeResources', undefined},
          {8, optional, bool, 'includeLinkedNotebooks', undefined},
          {9, optional, bool, 'includeExpunged', undefined},
          {10, optional, bool, 'includeNoteApplicationDataFullMap', undefined},
          {12, optional, bool, 'includeResourceApplicationDataFullMap', undefined},
          {13, optional, bool, 'includeNoteResourceApplicationDataFullMap', undefined},
          {17, optional, bool, 'includeSharedNotes', undefined},
          {16, optional, bool, 'omitSharedNotebooks', undefined},
          {11, optional, string, 'requireNoteContentClass', undefined},
          {15, optional, {set, string}, 'notebookGuids', sets:new()}]}
;

struct_info_ext('NoteFilter') ->
  {struct, [{1, optional, i32, 'order', undefined},
          {2, optional, bool, 'ascending', undefined},
          {3, optional, string, 'words', undefined},
          {4, optional, string, 'notebookGuid', undefined},
          {5, optional, {list, string}, 'tagGuids', []},
          {6, optional, string, 'timeZone', undefined},
          {7, optional, bool, 'inactive', undefined},
          {8, optional, string, 'emphasized', undefined},
          {9, optional, bool, 'includeAllReadableNotebooks', undefined},
          {15, optional, bool, 'includeAllReadableWorkspaces', undefined},
          {10, optional, string, 'context', undefined},
          {11, optional, string, 'rawWords', undefined},
          {12, optional, string, 'searchContextBytes', undefined}]}
;

struct_info_ext('NoteList') ->
  {struct, [{1, required, i32, 'startIndex', undefined},
          {2, required, i32, 'totalNotes', undefined},
          {3, required, {list, {struct, {'types_types', 'Note'}}}, 'notes', []},
          {4, optional, {list, string}, 'stoppedWords', []},
          {5, optional, {list, string}, 'searchedWords', []},
          {6, optional, i32, 'updateCount', undefined},
          {7, optional, string, 'searchContextBytes', undefined},
          {8, optional, string, 'debugInfo', undefined}]}
;

struct_info_ext('NoteMetadata') ->
  {struct, [{1, required, string, 'guid', undefined},
          {2, optional, string, 'title', undefined},
          {5, optional, i32, 'contentLength', undefined},
          {6, optional, i64, 'created', undefined},
          {7, optional, i64, 'updated', undefined},
          {8, optional, i64, 'deleted', undefined},
          {10, optional, i32, 'updateSequenceNum', undefined},
          {11, optional, string, 'notebookGuid', undefined},
          {12, optional, {list, string}, 'tagGuids', []},
          {14, optional, {struct, {'types_types', 'NoteAttributes'}}, 'attributes', #'NoteAttributes'{}},
          {20, optional, string, 'largestResourceMime', undefined},
          {21, optional, i32, 'largestResourceSize', undefined}]}
;

struct_info_ext('NotesMetadataList') ->
  {struct, [{1, required, i32, 'startIndex', undefined},
          {2, required, i32, 'totalNotes', undefined},
          {3, required, {list, {struct, {'note_store_types', 'NoteMetadata'}}}, 'notes', []},
          {4, optional, {list, string}, 'stoppedWords', []},
          {5, optional, {list, string}, 'searchedWords', []},
          {6, optional, i32, 'updateCount', undefined},
          {7, optional, string, 'searchContextBytes', undefined},
          {9, optional, string, 'debugInfo', undefined}]}
;

struct_info_ext('NotesMetadataResultSpec') ->
  {struct, [{2, optional, bool, 'includeTitle', undefined},
          {5, optional, bool, 'includeContentLength', undefined},
          {6, optional, bool, 'includeCreated', undefined},
          {7, optional, bool, 'includeUpdated', undefined},
          {8, optional, bool, 'includeDeleted', undefined},
          {10, optional, bool, 'includeUpdateSequenceNum', undefined},
          {11, optional, bool, 'includeNotebookGuid', undefined},
          {12, optional, bool, 'includeTagGuids', undefined},
          {14, optional, bool, 'includeAttributes', undefined},
          {20, optional, bool, 'includeLargestResourceMime', undefined},
          {21, optional, bool, 'includeLargestResourceSize', undefined}]}
;

struct_info_ext('NoteCollectionCounts') ->
  {struct, [{1, optional, {map, string, i32}, 'notebookCounts', dict:new()},
          {2, optional, {map, string, i32}, 'tagCounts', dict:new()},
          {3, optional, i32, 'trashCount', undefined}]}
;

struct_info_ext('NoteResultSpec') ->
  {struct, [{1, optional, bool, 'includeContent', undefined},
          {2, optional, bool, 'includeResourcesData', undefined},
          {3, optional, bool, 'includeResourcesRecognition', undefined},
          {4, optional, bool, 'includeResourcesAlternateData', undefined},
          {5, optional, bool, 'includeSharedNotes', undefined},
          {6, optional, bool, 'includeNoteAppDataValues', undefined},
          {7, optional, bool, 'includeResourceAppDataValues', undefined},
          {8, optional, bool, 'includeAccountLimits', undefined}]}
;

struct_info_ext('NoteEmailParameters') ->
  {struct, [{1, optional, string, 'guid', undefined},
          {2, optional, {struct, {'types_types', 'Note'}}, 'note', #'Note'{}},
          {3, optional, {list, string}, 'toAddresses', []},
          {4, optional, {list, string}, 'ccAddresses', []},
          {5, optional, string, 'subject', undefined},
          {6, optional, string, 'message', undefined}]}
;

struct_info_ext('NoteVersionId') ->
  {struct, [{1, required, i32, 'updateSequenceNum', undefined},
          {2, required, i64, 'updated', undefined},
          {3, required, i64, 'saved', undefined},
          {4, required, string, 'title', undefined},
          {5, optional, i32, 'lastEditorId', undefined}]}
;

struct_info_ext('RelatedQuery') ->
  {struct, [{1, optional, string, 'noteGuid', undefined},
          {2, optional, string, 'plainText', undefined},
          {3, optional, {struct, {'note_store_types', 'NoteFilter'}}, 'filter', #'NoteFilter'{}},
          {4, optional, string, 'referenceUri', undefined},
          {5, optional, string, 'context', undefined},
          {6, optional, string, 'cacheKey', undefined}]}
;

struct_info_ext('RelatedResult') ->
  {struct, [{1, optional, {list, {struct, {'types_types', 'Note'}}}, 'notes', []},
          {2, optional, {list, {struct, {'types_types', 'Notebook'}}}, 'notebooks', []},
          {3, optional, {list, {struct, {'types_types', 'Tag'}}}, 'tags', []},
          {4, optional, {list, {struct, {'types_types', 'NotebookDescriptor'}}}, 'containingNotebooks', []},
          {5, optional, string, 'debugInfo', undefined},
          {6, optional, {list, {struct, {'types_types', 'UserProfile'}}}, 'experts', []},
          {7, optional, {list, {struct, {'types_types', 'RelatedContent'}}}, 'relatedContent', []},
          {8, optional, string, 'cacheKey', undefined},
          {9, optional, i32, 'cacheExpires', undefined}]}
;

struct_info_ext('RelatedResultSpec') ->
  {struct, [{1, optional, i32, 'maxNotes', undefined},
          {2, optional, i32, 'maxNotebooks', undefined},
          {3, optional, i32, 'maxTags', undefined},
          {4, optional, bool, 'writableNotebooksOnly', undefined},
          {5, optional, bool, 'includeContainingNotebooks', undefined},
          {6, optional, bool, 'includeDebugInfo', undefined},
          {7, optional, i32, 'maxExperts', undefined},
          {8, optional, i32, 'maxRelatedContent', undefined},
          {9, optional, {set, i32}, 'relatedContentTypes', sets:new()}]}
;

struct_info_ext('UpdateNoteIfUsnMatchesResult') ->
  {struct, [{1, optional, {struct, {'types_types', 'Note'}}, 'note', #'Note'{}},
          {2, optional, bool, 'updated', undefined}]}
;

struct_info_ext('ShareRelationshipRestrictions') ->
  {struct, [{1, optional, bool, 'noSetReadOnly', undefined},
          {2, optional, bool, 'noSetReadPlusActivity', undefined},
          {3, optional, bool, 'noSetModify', undefined},
          {4, optional, bool, 'noSetFullAccess', undefined}]}
;

struct_info_ext('InvitationShareRelationship') ->
  {struct, [{1, optional, string, 'displayName', undefined},
          {2, optional, {struct, {'types_types', 'UserIdentity'}}, 'recipientUserIdentity', #'UserIdentity'{}},
          {3, optional, i32, 'privilege', undefined},
          {5, optional, i32, 'sharerUserId', undefined}]}
;

struct_info_ext('MemberShareRelationship') ->
  {struct, [{1, optional, string, 'displayName', undefined},
          {2, optional, i32, 'recipientUserId', undefined},
          {3, optional, i32, 'bestPrivilege', undefined},
          {4, optional, i32, 'individualPrivilege', undefined},
          {5, optional, {struct, {'note_store_types', 'ShareRelationshipRestrictions'}}, 'restrictions', #'ShareRelationshipRestrictions'{}},
          {6, optional, i32, 'sharerUserId', undefined}]}
;

struct_info_ext('ShareRelationships') ->
  {struct, [{1, optional, {list, {struct, {'note_store_types', 'InvitationShareRelationship'}}}, 'invitations', []},
          {2, optional, {list, {struct, {'note_store_types', 'MemberShareRelationship'}}}, 'memberships', []},
          {3, optional, {struct, {'note_store_types', 'ShareRelationshipRestrictions'}}, 'invitationRestrictions', #'ShareRelationshipRestrictions'{}}]}
;

struct_info_ext('ManageNotebookSharesParameters') ->
  {struct, [{1, optional, string, 'notebookGuid', undefined},
          {2, optional, string, 'inviteMessage', undefined},
          {3, optional, {list, {struct, {'note_store_types', 'MemberShareRelationship'}}}, 'membershipsToUpdate', []},
          {4, optional, {list, {struct, {'note_store_types', 'InvitationShareRelationship'}}}, 'invitationsToCreateOrUpdate', []},
          {5, optional, {list, {struct, {'types_types', 'UserIdentity'}}}, 'unshares', []}]}
;

struct_info_ext('ManageNotebookSharesError') ->
  {struct, [{1, optional, {struct, {'types_types', 'UserIdentity'}}, 'userIdentity', #'UserIdentity'{}},
          {2, optional, {struct, {'errors_types', 'EDAMUserException'}}, 'userException', #'EDAMUserException'{}},
          {3, optional, {struct, {'errors_types', 'EDAMNotFoundException'}}, 'notFoundException', #'EDAMNotFoundException'{}}]}
;

struct_info_ext('ManageNotebookSharesResult') ->
  {struct, [{1, optional, {list, {struct, {'note_store_types', 'ManageNotebookSharesError'}}}, 'errors', []}]}
;

struct_info_ext('SharedNoteTemplate') ->
  {struct, [{1, optional, string, 'noteGuid', undefined},
          {4, optional, i64, 'recipientThreadId', undefined},
          {2, optional, {list, {struct, {'types_types', 'Contact'}}}, 'recipientContacts', []},
          {3, optional, i32, 'privilege', undefined}]}
;

struct_info_ext('NotebookShareTemplate') ->
  {struct, [{1, optional, string, 'notebookGuid', undefined},
          {4, optional, i64, 'recipientThreadId', undefined},
          {2, optional, {list, {struct, {'types_types', 'Contact'}}}, 'recipientContacts', []},
          {3, optional, i32, 'privilege', undefined}]}
;

struct_info_ext('CreateOrUpdateNotebookSharesResult') ->
  {struct, [{1, optional, i32, 'updateSequenceNum', undefined},
          {2, optional, {list, {struct, {'types_types', 'SharedNotebook'}}}, 'matchingShares', []}]}
;

struct_info_ext('NoteShareRelationshipRestrictions') ->
  {struct, [{1, optional, bool, 'noSetReadNote', undefined},
          {2, optional, bool, 'noSetModifyNote', undefined},
          {3, optional, bool, 'noSetFullAccess', undefined}]}
;

struct_info_ext('NoteMemberShareRelationship') ->
  {struct, [{1, optional, string, 'displayName', undefined},
          {2, optional, i32, 'recipientUserId', undefined},
          {3, optional, i32, 'privilege', undefined},
          {4, optional, {struct, {'note_store_types', 'NoteShareRelationshipRestrictions'}}, 'restrictions', #'NoteShareRelationshipRestrictions'{}},
          {5, optional, i32, 'sharerUserId', undefined}]}
;

struct_info_ext('NoteInvitationShareRelationship') ->
  {struct, [{1, optional, string, 'displayName', undefined},
          {2, optional, i64, 'recipientIdentityId', undefined},
          {3, optional, i32, 'privilege', undefined},
          {5, optional, i32, 'sharerUserId', undefined}]}
;

struct_info_ext('NoteShareRelationships') ->
  {struct, [{1, optional, {list, {struct, {'note_store_types', 'NoteInvitationShareRelationship'}}}, 'invitations', []},
          {2, optional, {list, {struct, {'note_store_types', 'NoteMemberShareRelationship'}}}, 'memberships', []},
          {3, optional, {struct, {'note_store_types', 'NoteShareRelationshipRestrictions'}}, 'invitationRestrictions', #'NoteShareRelationshipRestrictions'{}}]}
;

struct_info_ext('ManageNoteSharesParameters') ->
  {struct, [{1, optional, string, 'noteGuid', undefined},
          {2, optional, {list, {struct, {'note_store_types', 'NoteMemberShareRelationship'}}}, 'membershipsToUpdate', []},
          {3, optional, {list, {struct, {'note_store_types', 'NoteInvitationShareRelationship'}}}, 'invitationsToUpdate', []},
          {4, optional, {list, i32}, 'membershipsToUnshare', []},
          {5, optional, {list, i64}, 'invitationsToUnshare', []}]}
;

struct_info_ext('ManageNoteSharesError') ->
  {struct, [{1, optional, i64, 'identityID', undefined},
          {2, optional, i32, 'userID', undefined},
          {3, optional, {struct, {'errors_types', 'EDAMUserException'}}, 'userException', #'EDAMUserException'{}},
          {4, optional, {struct, {'errors_types', 'EDAMNotFoundException'}}, 'notFoundException', #'EDAMNotFoundException'{}}]}
;

struct_info_ext('ManageNoteSharesResult') ->
  {struct, [{1, optional, {list, {struct, {'note_store_types', 'ManageNoteSharesError'}}}, 'errors', []}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

struct_names() ->
  ['SyncState', 'SyncChunk', 'SyncChunkFilter', 'NoteFilter', 'NoteList', 'NoteMetadata', 'NotesMetadataList', 'NotesMetadataResultSpec', 'NoteCollectionCounts', 'NoteResultSpec', 'NoteEmailParameters', 'NoteVersionId', 'RelatedQuery', 'RelatedResult', 'RelatedResultSpec', 'UpdateNoteIfUsnMatchesResult', 'ShareRelationshipRestrictions', 'InvitationShareRelationship', 'MemberShareRelationship', 'ShareRelationships', 'ManageNotebookSharesParameters', 'ManageNotebookSharesError', 'ManageNotebookSharesResult', 'SharedNoteTemplate', 'NotebookShareTemplate', 'CreateOrUpdateNotebookSharesResult', 'NoteShareRelationshipRestrictions', 'NoteMemberShareRelationship', 'NoteInvitationShareRelationship', 'NoteShareRelationships', 'ManageNoteSharesParameters', 'ManageNoteSharesError', 'ManageNoteSharesResult'].

enum_info('ShareRelationshipPrivilegeLevel') ->
  [
    {'READ_NOTEBOOK', 0},
    {'READ_NOTEBOOK_PLUS_ACTIVITY', 10},
    {'MODIFY_NOTEBOOK_PLUS_ACTIVITY', 20},
    {'FULL_ACCESS', 30}
  ];

enum_info(_) -> erlang:error(function_clause).

enum_names() ->
  ['ShareRelationshipPrivilegeLevel'].

exception_names() ->
  [].

